services:
  - type: web
    name: rls-simulation
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    rootDir: "backend"
